name: ✨ Feature
description: "⚠️ For Project Maintainers: Create a Feature work item"
type: "Feature"
body:
  - type: checkboxes
    attributes:
      label: Is this the right issue type?
      description: "If you're not involved in work planning for this project, you're probably in the wrong place."
      options:
        - label: "Yes, I'm planning work for this project team."
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: |
        A short description of the work item
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: A breakdown of acceptance criteria to determine this work item's definition of done.
      value: |
        - [ ] Criterion A is met.
        - [ ] Criterion B is met.
        - [ ] Tests pass.
        - [ ] Documentation added.
    validations:
      required: true
